#!/usr/bin/env python3
"""Build the PS3 Wireless Stereo Headset Hub as a Windows **onedir** app.

Usage (from anywhere):

    python packaging/build_exe.py              # build into <repo>/build
    python packaging/build_exe.py --clean      # wipe build/ first
    python packaging/build_exe.py --no-zip     # skip the distributable zip
    python packaging/build_exe.py --skip-deps  # skip the dependency check

Or simply double-click ``packaging\\build.bat``.

Output layout (relative to the repository root):

    build/PS3HeadsetHub/PS3HeadsetHub.exe   launch this
    build/PS3HeadsetHub/_internal/          its libraries (keep together)
    build/PS3HeadsetHub-<version>-win64.zip self-contained distributable
    build/build-report.txt                  version, commit, size, sha256
    build/_work/                            PyInstaller intermediates

Why onedir (instead of the previous one-file exe): the app starts
immediately - there is no self-extraction of a 28 MiB archive to a temp
folder on every launch - and antivirus products quarantine self-extracting
game-style executables far more often than plain directory builds.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import importlib.metadata as importlib_metadata
import json
import os
import shutil
import subprocess
import sys
import time
import zipfile
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent      # .../app
REPO_ROOT = APP_DIR.parent                            # repository root
BUILD_DIR = REPO_ROOT / "build"
WORK_DIR = BUILD_DIR / "_work"
APP_BUNDLE = BUILD_DIR / "PS3HeadsetHub"              # onedir folder
EXE_PATH = APP_BUNDLE / "PS3HeadsetHub.exe"
SPEC_FILE = APP_DIR / "packaging" / "ps3hub.spec"
VERSION_FILE = APP_DIR / "packaging" / "version_info.txt"
EXE_NAME = "PS3HeadsetHub"
#: Install helpers shipped at the root of the distributable zip: a user
#: extracts, double-clicks Install.cmd, and the app lands in
#: %LOCALAPPDATA% with shortcuts and tray autostart.
HELPER_FILES = (
    ("install.ps1", "install.ps1"),
    ("Install.cmd", "Install.cmd"),
    ("uninstall.cmd", "uninstall.cmd"),
)

#: Runtime dependencies the packaged application needs. hidapi/ttkbootstrap
#: are hard requirements; sounddevice/numpy power the native loopback DSP
#: (the FxSound route works without them).
REQUIRED = ("hidapi", "ttkbootstrap", "pillow", "numpy")
OPTIONAL = ("sounddevice",)


def log(message: str) -> None:
    print(f"[build] {message}", flush=True)


def fail(message: str) -> None:
    print(f"[build] ERROR: {message}", file=sys.stderr, flush=True)
    raise SystemExit(1)


def read_version() -> str:
    text = (APP_DIR / "ps3hub" / "__init__.py").read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith("APP_VERSION"):
            return line.split("=")[1].strip().strip('"')
    return "0.0.0"


def check_dependencies() -> None:
    """Verify the build tools and runtime packages are importable."""
    try:
        importlib.import_module("PyInstaller")
    except ImportError:
        fail("PyInstaller is not installed. Run:\n"
             "    python -m pip install pyinstaller")
    missing = []
    for package in REQUIRED:
        try:
            importlib_metadata.version(package)
        except importlib_metadata.PackageNotFoundError:
            missing.append(package)
    if missing:
        fail("Missing runtime packages: " + ", ".join(missing) +
             "\n    python -m pip install -r requirements.txt "
             "numpy")
    for package in OPTIONAL:
        try:
            version = importlib_metadata.version(package)
        except importlib_metadata.PackageNotFoundError:
            version = "absent (the native loopback backend will be skipped)"
        log(f"dependency {package}: {version}")


def write_version_resource() -> Path:
    """Emit a Windows VERSIONINFO file from APP_VERSION, return its path."""
    app_version = read_version()
    parts = [int(piece) for piece in app_version.split(".")[:4]]
    while len(parts) < 4:
        parts.append(0)
    filevers = tuple(parts)  # type: ignore[assignment]
    dotted = ".".join(str(part) for part in filevers)
    product = f"PS3 Wireless Stereo Headset Hub {app_version}"

    VERSION_FILE.parent.mkdir(parents=True, exist_ok=True)
    version_file = VERSION_FILE
    version_file.write_text(f"""# UTF-8
# Generated by packaging/build_exe.py from ps3hub.APP_VERSION - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers!r},
    prodvers={filevers!r},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'keparyt'),
        StringStruct('FileDescription', 'PS3 Wireless Stereo Headset Hub for Windows'),
        StringStruct('FileVersion', '{dotted}'),
        StringStruct('InternalName', '{EXE_NAME}'),
        StringStruct('LegalCopyright', ''),
        StringStruct('OriginalFilename', '{EXE_NAME}.exe'),
        StringStruct('ProductName', 'PS3 Wireless Stereo Headset Hub'),
        StringStruct('ProductVersion', '{product}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ]
)
""", encoding="utf-8")
    log(f"version resource: {app_version} -> {version_file.name}")
    return version_file


def git_info() -> dict[str, str]:
    """Best-effort git metadata for the build report."""
    info = {"commit": "unknown", "branch": "unknown", "dirty": "unknown"}
    try:
        info["commit"] = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True, timeout=15).stdout.strip()
        info["branch"] = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True, timeout=15).stdout.strip()
        dirty = subprocess.run(
            ["git", "status", "--porcelain"], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True, timeout=15).stdout.strip()
        info["dirty"] = "yes" if dirty else "no"
    except Exception:
        pass
    return info


def run_pyinstaller(version_file: Path) -> None:
    """Invoke PyInstaller with the checked-in onedir spec."""
    command = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--distpath", str(BUILD_DIR),
        "--workpath", str(WORK_DIR),
        str(SPEC_FILE),
    ]
    log("running: " + " ".join(command))
    started = time.monotonic()
    result = subprocess.run(command, cwd=APP_DIR)
    elapsed = time.monotonic() - started
    if result.returncode != 0:
        fail(f"PyInstaller exited with code {result.returncode} "
             f"after {elapsed:.0f}s")
    if not EXE_PATH.exists():
        fail(f"PyInstaller reported success but {EXE_PATH} does not exist")
    log(f"built in {elapsed:.0f}s")


def folder_stats(bundle: Path) -> tuple[int, int]:
    """Total bytes and file count of the onedir bundle."""
    total = 0
    count = 0
    for path in bundle.rglob("*"):
        if path.is_file():
            total += path.stat().st_size
            count += 1
    return total, count


def copy_install_helpers() -> None:
    """Place install/uninstall helpers at the zip root, next to the folder."""
    for source_name, target_name in HELPER_FILES:
        source = APP_DIR / "packaging" / source_name
        if not source.exists():
            log(f"WARNING: install helper missing: {source}")
            continue
        shutil.copy2(source, BUILD_DIR / target_name)
    log("install helpers: Install.cmd / install.ps1 / uninstall.cmd")


def make_zip(bundle: Path, version: str) -> Path:
    """Zip the onedir bundle plus the install helpers into a distributable."""
    zip_path = BUILD_DIR / f"{EXE_NAME}-{version}-win64.zip"
    if zip_path.exists():
        zip_path.unlink()
    log(f"zipping -> {zip_path.name}")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for path in sorted(bundle.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(bundle.parent))
        for _source, target_name in HELPER_FILES:
            helper = BUILD_DIR / target_name
            if helper.exists():
                zf.write(helper, helper.name)
    size = zip_path.stat().st_size
    log(f"zip written: {size / (1 << 20):.1f} MiB")
    return zip_path


def write_report(version: str, zip_path: Path | None) -> None:
    """Drop a build-report.txt next to the exe: what, when, how big."""
    exe_size = EXE_PATH.stat().st_size
    total, count = folder_stats(APP_BUNDLE)
    digest = hashlib.sha256(EXE_PATH.read_bytes()).hexdigest()

    lines = [
        "PS3 Wireless Stereo Headset Hub - build report",
        f"generated : {time.strftime('%Y-%m-%d %H:%M:%S')}",
        f"version   : {version}",
        f"layout    : onedir ({count} files, {total / (1 << 20):.1f} MiB total)",
        f"artifact  : {EXE_PATH}",
        f"exe size  : {exe_size:,} bytes ({exe_size / (1 << 20):.1f} MiB)",
    ]
    if zip_path is not None:
        zip_size = zip_path.stat().st_size
        zip_digest = hashlib.sha256(zip_path.read_bytes()).hexdigest()
        lines.append(f"zip       : {zip_path.name} "
                     f"({zip_size / (1 << 20):.1f} MiB, "
                     f"sha256 {zip_digest[:16]}...)")
    git = git_info()
    lines.append(f"commit    : {git['commit']} (branch {git['branch']}, "
                 f"dirty: {git['dirty']})")
    lines.append(f"exe sha256: {digest}")
    report = "\n".join(lines) + "\n"
    (BUILD_DIR / "build-report.txt").write_text(report, encoding="utf-8")
    log(report.replace("\n", "\n[build]   "))


def verify_bundle() -> None:
    """Sanity-check the onedir bundle before calling it done."""
    internal = APP_BUNDLE / "_internal"
    if not internal.is_dir():
        fail(f"{internal} is missing - the onedir bundle is incomplete")
    for required in ("EQExamples",):
        if not (internal / required).is_dir():
            fail(f"{internal / required} is missing - the Examples row "
                 "would be empty in the packaged app")
    log("bundle layout verified: _internal + EQExamples present")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build the Hub as a onedir Windows app into /build.")
    parser.add_argument("--clean", action="store_true",
                        help="delete build/ before building")
    parser.add_argument("--no-zip", action="store_true",
                        help="skip the distributable zip")
    parser.add_argument("--skip-deps", action="store_true",
                        help="skip the dependency sanity check")
    args = parser.parse_args(argv)

    if os.name != "nt":
        # PyInstaller builds for the running OS; a Windows app needs Windows.
        log("WARNING: not running on Windows - the artifact will not be a "
            "working Windows executable.")

    if not args.skip_deps:
        check_dependencies()

    if args.clean and BUILD_DIR.exists():
        log(f"removing {BUILD_DIR}")
        shutil.rmtree(BUILD_DIR, ignore_errors=True)

    version = read_version()
    version_file = write_version_resource()
    run_pyinstaller(version_file)
    verify_bundle()
    copy_install_helpers()
    zip_path = None if args.no_zip else make_zip(APP_BUNDLE, version)
    write_report(version, zip_path)
    log(f"DONE: {EXE_PATH}")
    log("users: extract the zip and double-click Install.cmd")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
