#!/usr/bin/env python3
"""Build the PS3 Wireless Stereo Headset Hub as a single Windows executable.

Usage (from anywhere):

    python packaging/build_exe.py            # build into <repo>/build
    python packaging/build_exe.py --clean    # wipe build/ first
    python packaging/build_exe.py --skip-deps  # skip the dependency check

Output layout (relative to the repository root):

    build/PS3HeadsetHub.exe      the application, one windowed exe
    build/build-report.txt       version, git commit, size, sha256
    build/_work/                 PyInstaller intermediates (safe to delete)

The exe carries the version resource from ``ps3hub.APP_VERSION`` (shown in
Explorer's Properties dialog), the bundled EQExamples curves, and
ttkbootstrap's icon fonts, so toasts and the Examples row work in the
packaged application exactly as in development.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import importlib.metadata as importlib_metadata
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent      # .../app
REPO_ROOT = APP_DIR.parent                            # repository root
BUILD_DIR = REPO_ROOT / "build"
WORK_DIR = BUILD_DIR / "_work"
DIST_DIR = BUILD_DIR                                  # the exe lands here
SPEC_FILE = APP_DIR / "packaging" / "ps3hub.spec"
EXE_NAME = "PS3HeadsetHub"
#: Written beside the spec so the spec can always find it (SPECPATH),
#: regardless of where PyInstaller's workpath points.
VERSION_FILE = APP_DIR / "packaging" / "version_info.txt"

#: Runtime dependencies the packaged application needs. hidapi/ttkbootstrap
#: are hard requirements; sounddevice is optional (the native loopback DSP
#: works without it, the FxSound route never touches it).
REQUIRED = ("hidapi", "ttkbootstrap", "pillow")
OPTIONAL = ("sounddevice", "numpy")


def log(message: str) -> None:
    print(f"[build] {message}", flush=True)


def fail(message: str) -> "NoReturn":  # type: ignore[valid-type]
    print(f"[build] ERROR: {message}", file=sys.stderr, flush=True)
    raise SystemExit(1)


def check_dependencies() -> None:
    """Verify the build tools and runtime packages are importable."""
    try:
        importlib.import_module("PyInstaller")
    except ImportError:
        fail("PyInstaller is not installed. Run:\n"
             "    python -m pip install pyinstaller")
    missing = []
    for package in REQUIRED:
        try:
            importlib_metadata.version(package)
        except importlib_metadata.PackageNotFoundError:
            missing.append(package)
    if missing:
        fail("Missing runtime packages: " + ", ".join(missing) +
             "\n    python -m pip install -r requirements.txt")
    for package in OPTIONAL:
        try:
            version = importlib_metadata.version(package)
        except importlib_metadata.PackageNotFoundError:
            version = "absent (that backend will be skipped in the exe)"
        log(f"dependency {package}: {version}")


def write_version_resource() -> Path:
    """Emit a Windows VERSIONINFO file from APP_VERSION, return its path."""
    version_text = APP_DIR / "ps3hub" / "__init__.py"
    app_version = "0.0.0"
    for line in version_text.read_text(encoding="utf-8").splitlines():
        if line.startswith("APP_VERSION"):
            app_version = line.split("=")[1].strip().strip('"')
            break
    parts = [int(piece) for piece in app_version.split(".")[:4]]
    while len(parts) < 4:
        parts.append(0)
    filevers = tuple(parts)  # type: ignore[assignment]
    dotted = ".".join(str(part) for part in filevers)
    product = f"PS3 Wireless Stereo Headset Hub {app_version}"

    VERSION_FILE.parent.mkdir(parents=True, exist_ok=True)
    version_file = VERSION_FILE
    version_file.write_text(f"""# UTF-8
# Generated by packaging/build_exe.py from ps3hub.APP_VERSION - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers!r},
    prodvers={filevers!r},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'keparyt'),
        StringStruct('FileDescription', 'PS3 Wireless Stereo Headset Hub for Windows'),
        StringStruct('FileVersion', '{dotted}'),
        StringStruct('InternalName', '{EXE_NAME}'),
        StringStruct('LegalCopyright', ''),
        StringStruct('OriginalFilename', '{EXE_NAME}.exe'),
        StringStruct('ProductName', 'PS3 Wireless Stereo Headset Hub'),
        StringStruct('ProductVersion', '{product}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ]
)
""", encoding="utf-8")
    log(f"version resource: {app_version} -> {version_file.name}")
    return version_file


def git_info() -> dict[str, str]:
    """Best-effort git metadata for the build report."""
    info = {"commit": "unknown", "branch": "unknown", "dirty": "unknown"}
    try:
        info["commit"] = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True, timeout=15).stdout.strip()
        info["branch"] = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True, timeout=15).stdout.strip()
        dirty = subprocess.run(
            ["git", "status", "--porcelain"], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True, timeout=15).stdout.strip()
        info["dirty"] = "yes" if dirty else "no"
    except Exception:
        pass
    return info


def run_pyinstaller(version_file: Path) -> Path:
    """Invoke PyInstaller with the checked-in spec; return the exe path."""
    command = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--distpath", str(DIST_DIR),
        "--workpath", str(WORK_DIR),
        str(SPEC_FILE),
    ]
    log("running: " + " ".join(command))
    started = time.monotonic()
    result = subprocess.run(command, cwd=APP_DIR)
    elapsed = time.monotonic() - started
    if result.returncode != 0:
        fail(f"PyInstaller exited with code {result.returncode} "
             f"after {elapsed:.0f}s")
    exe = DIST_DIR / f"{EXE_NAME}.exe"
    if not exe.exists():
        fail(f"PyInstaller reported success but {exe} does not exist")
    log(f"built in {elapsed:.0f}s")
    return exe


def write_report(exe: Path) -> None:
    """Drop a build-report.txt next to the exe: what, when, how big."""
    version = "unknown"
    for line in (APP_DIR / "ps3hub" / "__init__.py").read_text(
            encoding="utf-8").splitlines():
        if line.startswith("APP_VERSION"):
            version = line.split("=")[1].strip().strip('"')
            break
    size = exe.stat().st_size
    digest = hashlib.sha256()
    with exe.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    git = git_info()
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    report = (
        f"PS3 Wireless Stereo Headset Hub - build report\n"
        f"generated : {stamp}\n"
        f"version   : {version}\n"
        f"commit    : {git['commit']} (branch {git['branch']}, "
        f"dirty: {git['dirty']})\n"
        f"artifact  : {exe}\n"
        f"size      : {size:,} bytes ({size / (1 << 20):.1f} MiB)\n"
        f"sha256    : {digest.hexdigest()}\n"
    )
    (BUILD_DIR / "build-report.txt").write_text(report, encoding="utf-8")
    log(report.replace("\n", "\n[build]   "))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build the Hub as a single Windows executable into /build.")
    parser.add_argument("--clean", action="store_true",
                        help="delete build/ before building")
    parser.add_argument("--skip-deps", action="store_true",
                        help="skip the dependency sanity check")
    args = parser.parse_args(argv)

    if os.name != "nt":
        # PyInstaller builds for the running OS; a Windows exe needs Windows.
        log("WARNING: not running on Windows - the artifact will not be a "
            "working Windows executable.")

    if not args.skip_deps:
        check_dependencies()

    if args.clean and BUILD_DIR.exists():
        log(f"removing {BUILD_DIR}")
        shutil.rmtree(BUILD_DIR, ignore_errors=True)

    version_file = write_version_resource()
    exe = run_pyinstaller(version_file)
    write_report(exe)
    log(f"DONE: {exe}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
