#!/usr/bin/env python3
"""Build the standalone GUI installer: ``PS3HeadsetHubInstaller.exe``.

Run it after :mod:`packaging.build_exe` - the installer packs the existing
onedir application folder into a single windowed exe (stdlib + tkinter only,
so it stays small and needs no admin rights or extra runtime). Usage::

    python packaging/build_installer.py             # -> <repo>/build/
    python packaging/build_installer.py --skip-smoke

The result is a proper installer with a window (install location, tray
autostart and desktop-shortcut options, live log) that can also download and
silently install FxSound. Headless mode: ``PS3HeadsetHubInstaller.exe
--silent``.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import shutil
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_exe  # noqa: E402 - same directory helper module

APP_DIR = build_exe.APP_DIR
BUILD_DIR = build_exe.BUILD_DIR
PAYLOAD_DIR = build_exe.APP_BUNDLE
INSTALLER_EXE = BUILD_DIR / "PS3HeadsetHubInstaller.exe"
SPEC_FILE = APP_DIR / "packaging" / "installer.spec"
STAGING = APP_DIR / "packaging" / "_installer_staging"


def write_installer_version_info() -> Path:
    """Emit a VERSIONINFO resource describing the installer itself."""
    app_version = build_exe.read_version()
    parts = [int(piece) for piece in app_version.split(".")[:4]]
    while len(parts) < 4:
        parts.append(0)
    filevers = tuple(parts)  # type: ignore[assignment]
    dotted = ".".join(str(part) for part in filevers)
    name = "PS3HeadsetHubInstaller"
    product = f"PS3 Wireless Stereo Headset Hub {app_version} installer"

    STAGING.mkdir(parents=True, exist_ok=True)
    version_file = STAGING / "installer_version_info.txt"
    version_file.write_text(f"""# UTF-8
# Generated by packaging/build_installer.py from ps3hub.APP_VERSION - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers!r},
    prodvers={filevers!r},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'keparyt'),
        StringStruct('FileDescription', 'Installer for the PS3 Wireless Stereo Headset Hub'),
        StringStruct('FileVersion', '{dotted}'),
        StringStruct('InternalName', '{name}'),
        StringStruct('LegalCopyright', ''),
        StringStruct('OriginalFilename', '{name}.exe'),
        StringStruct('ProductName', 'PS3 Wireless Stereo Headset Hub'),
        StringStruct('ProductVersion', '{product}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ]
)
""", encoding="utf-8")
    build_exe.log(f"installer version resource: {app_version}")
    return version_file


def run_pyinstaller() -> None:
    command = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--distpath", str(BUILD_DIR),
        "--workpath", str(BUILD_DIR / "_work"),
        str(SPEC_FILE),
    ]
    build_exe.log("running: " + " ".join(command))
    started = time.monotonic()
    result = subprocess.run(command, cwd=APP_DIR)
    elapsed = time.monotonic() - started
    if result.returncode != 0:
        build_exe.fail(f"PyInstaller exited with code {result.returncode} "
                       f"after {elapsed:.0f}s")
    if not INSTALLER_EXE.exists():
        build_exe.fail("PyInstaller reported success but "
                       f"{INSTALLER_EXE} does not exist")
    build_exe.log(f"installer built in {elapsed:.0f}s")


def smoke_test() -> None:
    """Run --help so a broken bootloader or script fails here, not for users."""
    result = subprocess.run([str(INSTALLER_EXE), "--help"], timeout=120)
    if result.returncode != 0:
        build_exe.fail(f"installer --help exited with {result.returncode}")


def append_to_report() -> None:
    """Add an installer line to the build report build_exe.py wrote."""
    report = BUILD_DIR / "build-report.txt"
    if not report.exists():
        return
    size = INSTALLER_EXE.stat().st_size
    digest = hashlib.sha256(INSTALLER_EXE.read_bytes()).hexdigest()
    with report.open("a", encoding="utf-8") as sink:
        sink.write(f"installer : {INSTALLER_EXE.name} "
                   f"({size / (1 << 20):.1f} MiB, sha256 {digest[:16]}...)\n")
    build_exe.log(f"installer : {INSTALLER_EXE.name} "
                  f"({size / (1 << 20):.1f} MiB, sha256 {digest[:16]}...)")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build PS3HeadsetHubInstaller.exe into /build.")
    parser.add_argument("--skip-smoke", action="store_true",
                        help="skip running --help against the built exe")
    args = parser.parse_args(argv)

    try:
        importlib.import_module("PyInstaller")
    except ImportError:
        build_exe.fail("PyInstaller is not installed. Run:\n"
                       "    python -m pip install pyinstaller")

    if not (PAYLOAD_DIR / (build_exe.EXE_NAME + ".exe")).exists():
        build_exe.fail(
            f"the application payload is missing: {PAYLOAD_DIR}\n"
            "    Run packaging/build_exe.py first (make_release.bat does).")

    write_installer_version_info()
    if INSTALLER_EXE.exists():
        INSTALLER_EXE.unlink()
    run_pyinstaller()
    if not args.skip_smoke:
        smoke_test()
    append_to_report()
    build_exe.log(f"DONE: {INSTALLER_EXE}")
    build_exe.log("users: double-click PS3HeadsetHubInstaller.exe "
                  "(or run it with --silent for a headless install)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
